#eureka:
#  instance:
#    preferIpAddress: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#  client:
#    serviceUrl:
#      defaultZone: http://192.168.26.128:8761/eureka/
spring:
  application:
    name: authenticationservice
server:
  port: 9000 
#  cloud:
#    config:
#      profile: gs
#      discovery:
#        enabled: true
#        service-id: configservice
mybatis:
  type-aliases-package: com.lzh.medicalface.model.entity
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
    default-fetch-size: 100