server:
  port: 9112
spring:
  #application:
  #   name: authenticationservice
  #datasource:
    #url: jdbc:mysql://192.168.121.18:3306/testdb?characterEncoding=UTF-8
    #url: jdbc:mysql://192.168.26.128:3306/testdb?characterEncoding=UTF-8
    #url: ${spring.datasource.url}
    #username: ${spring.datasource.username}
    #password: ${spring.datasource.password}
    #driver-class-name: ${spring.datasource.driver-class-name}
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




