server:
  port: 9112
spring:
  #application:
  #   name: authenticationservice
  datasource:
    #url: jdbc:mysql://47.93.193.177:3306/test?useSSL=false
    url: jdbc:mysql://192.168.26.128:3306/zuul_db?useSSL=false
    #url: jdbc:mysql://192.168.121.5:3306/zuul_db?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




